### ISSUE TITLE
make into a web extension

### ISSUE THREAD

**Issue by swyxio** [netlify/netlify-chrome-extension#1]
thanks to the prompting of @birtles, we can make this extension more accessible for non chrome users: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

free for anyone to pick up e.g. @dance2die if you wish

**Comment by dance2die** [comment]
I haven't been using FireFox but sounds like a fun project.
 
Let me know if I can start as late as this Saturday.
If someone else can start before 11/17/2018, you can grab this 😄

**Comment by nero2009** [comment]
Currently working on this. 
The pop.html is not updating. that is where i am at now

**Comment by swyxio** [comment]
yeah making the extensions work is hard. its an event system, make sure you are console.logging every step to understand how the messages are passed

**Comment by nero2009** [comment]
I have been able to make it work on firefox, the problem I was having was passing the `location` variable from the `content script` to the `popup.js`, I was able to work around it by sending the variable to the `background script` first then to the `popup.js`.

**Comment by nero2009** [comment]
Should I create a new repository for the firefox extension or just make a PR

**Comment by swyxio** [comment]
make a PR! :) thank you for working on it!
