### ISSUE TITLE
False positives have become consistent

### ISSUE THREAD

**Issue by philhawksworth** [netlify/netlify-chrome-extension#4]
Results for me are now that the extension now identifies all sites as being Netlify sites irrespective of the actual result.

This is happening on every URL I visit.

**Comment by swyxio** [comment]
does it look like this

![image](https://user-images.githubusercontent.com/6764957/50641885-56fd3a00-0fa4-11e9-83ed-d426da994efc.png)

or does it actually show the popup saying "it's a Netlify site!"

**Comment by philhawksworth** [comment]
aha...

It looks like that when it's not a Netlify site, and like this when it is (showing this site has non-public build logs, I guess):

<img width="432" alt="screenshot 2019-01-03 at 14 49 03" src="https://user-images.githubusercontent.com/5865/50643769-e126ad80-0f66-11e9-86c5-31f43d886520.png">

So I guess this might just be the icon status being wrong rather than the detection itself.

**Comment by swyxio** [comment]
yes. something seems to have changed in chrome, and of course they gave no notice of it anywhere.

similar extension: https://github.com/tsriram/is-gatsby also broken in the same way

**Comment by swyxio** [comment]
filed https://github.com/tsriram/is-gatsby/issues/1

no idea where to report this if it is in fact a chrome bug

**Comment by tsriram** [comment]
Looks like [pageAction.hide](https://developer.chrome.com/extensions/pageAction#method-hide) API for Chrome extension is not graying out the icon. I could see the message that a site is not a Gatsby site, but the icon isn't grayed out like earlier.

![image](https://user-images.githubusercontent.com/450559/50652242-e823df00-0fab-11e9-9d65-c340cd8d86c4.png)

One not-so-elegant way would be to use a gray icon explicitly. Need to figure out if there's a change in extension API.

**Comment by swyxio** [comment]
yea. any idea where this is documented? i searched for quite a while and couldnt find any changelog

**Comment by tsriram** [comment]
Not really! [Documentation](https://developer.chrome.com/extensions/pageAction#method-hide) still says the icon will be grayed out on `pageAction.hide`. I too couldn't find any changelog :man_shrugging:

**Comment by swyxio** [comment]
i noticed that react devtools still works - whatever method they use isn't broken. have to look into it

**Comment by swyxio** [comment]
yeah they have a "disabled" icon https://github.com/facebook/react-devtools/blob/b2c1ae61b5273aa307cc765ecdc7258378059675/shells/chrome/manifest.json as default

**Comment by swyxio** [comment]
i have cobbled together a crappy disabled netlify icon and pushed to chrome app store - should be approved in a couple days.

**Comment by swyxio** [comment]
fixed in 1.2.4


 if you havent tried the Netlify Browser Extension, we recently fixed a nasty bug where chrome broke our light-up functionality when you’re on a netlify hosted site: https://chrome.google.com/webstore/detail/netlify-browser-extension/dkhfpnphbcckigklfkaemnjdmghhcaoh in v1.2.4. thanks @phil for report
