### ISSUE TITLE
"Deploy to Netlify" button showing error on click

### ISSUE THREAD

**Issue by a9kitkumar** [netlify/netlify-chrome-extension#8]
I have placed the "deploy to netlify" button in react app and it is working fine here. After that I made a build of the project and uploaded it on the server, then after clicking the button I got following error: **app.netlify.com refused to connect.**

Please give any suggestion, thanks

**Comment by swyxio** [comment]
why are you connecting to app.netlify.com?

this repo is for the netlify browser extension, are you trying to get support for your own netlify project? if so file a question in community.netlify.com please.
